kevin-lee/kevin-docker

.gitignore, sbt/java11/Dockerfile, sbt/java8/Dockerfile
Added: sbt with java8 and java11
=> Added: sbt with java8 and java11

polynote-spark/Dockerfile, polynote-spark/config.yml, polynote-spark/docker-build.sh, polynote-spark/docker-run.sh, polynote/Dockerfile, polynote/config.yml, polynote/docker-build.sh, polynote/docker-run.sh
Added: Polynote and Polynote with Spark
Polynote: https://polynote.org/
=> Added: Polynote and Polynote with Spark

polynote-spark/Dockerfile, polynote/Dockerfile
Upgraded: Polynote 0.2.9 => 0.2.11
=> Upgraded: Polynote 0.2.9 => 0.2.11

polynotes/polynote-python/Dockerfile, polynotes/polynote-python/README.md, polynotes/polynote-python/config.yml, polynotes/polynote-python/docker-build.sh, polynotes/polynote-python/docker-run.sh
Added: Polynote with Python support
=> Added: Polynote with Python support

polynotes/polynote-python/Dockerfile, polynotes/polynote-python/README.md, polynotes/polynote-spark-python/Dockerfile, polynotes/polynote-spark-python/README.md, polynotes/polynote-spark/Dockerfile, polynotes/polynote-spark/README.md, polynotes/polynote/Dockerfile, polynotes/polynote/README.md
Changed: Scala `2.11` => `2.12`
=> Changed: Scala 2.11 => 2.12

polynotes/polynote-spark-python/Dockerfile
Changed: Installed Spark and pyspark have the same version
=> Changed: Installed Spark and pyspark have the same version

polynotes/polynote-python/Dockerfile, polynotes/polynote-spark-python/Dockerfile, polynotes/polynote-spark/Dockerfile, polynotes/polynote/Dockerfile
Upgraded: Polynote 0.2.11 => 0.2.12 (Fixed: JSON parse bug)
=> Upgraded: Polynote 0.2.11 => 0.2.12 (Fixed: JSON parse bug)

sbt/java11-jekyll/Dockerfile, sbt/java11-jekyll/README.md, sbt/java8-jekyll/Dockerfile, sbt/java8-jekyll/README.md
Added: `sbt-java8-jekyll` and `sbt-java11-jekyll`
=> Added: sbt-java8-jekyll and sbt-java11-jekyll

sbt/java11/Dockerfile, sbt/java8/Dockerfile
Added: `sbt sbtVersion` to make it download the latest sbt
=> Added: sbt sbtVersion to make it download the latest sbt

sbt/java11/Dockerfile, sbt/java8/Dockerfile
=> Fixed: Dockerfile

sbt/java11/Dockerfile, sbt/java8/Dockerfile
Updated: Ways to install AdoptOpenJDK and sbt
=> Updated: Ways to install AdoptOpenJDK and sbt

sbt/java11/Dockerfile, sbt/java8/Dockerfile
=> Updated: sbt installation

sbt/java11/Dockerfile, sbt/java11/README.md, sbt/java8/Dockerfile, sbt/java8/README.md
Fix `JAVA_HOME` in `sbt/java8` and `sbt/java11`
=> Fix `JAVA_HOME` in `sbt/java8` and `sbt/java11`

.github/workflows/docker-publish.yml
Update: GitHub Actions config to publish multiple images to GitHub Packages
=> Update: GitHub Actions config to publish multiple images to GitHub Packages

.github/workflows/docker-publish.yml
Update: GitHub Actions config to Docker images for multi-platforms
=> Update: GitHub Actions config to Docker images for multi-platforms

.github/workflows/docker-publish.yml, sbt/java17/Dockerfile, sbt/java17/README.md
Update: GitHub Actions config - add `sbt/java17`
=> Update: GitHub Actions config - add sbt/java17

sbt/java11/README.md, sbt/java17/README.md, sbt/java8/README.md
Update: `README.md` files of `sbt/java8`, `sbt/java11` and `sbt/java17`
=> Update: `README.md` files of `sbt/java8`, `sbt/java11` and `sbt/java17`

.github/workflows/docker-publish.yml, sbt/java11-node/Dockerfile, sbt/java11-node/README.md, sbt/java17-node/Dockerfile, sbt/java17-node/README.md, sbt/java8-node/Dockerfile, sbt/java8-node/README.md
Update: GitHub Actions config - Add `sbt/java8-node`,`sbt/java11-node` and `sbt/java17-node`
=> Update: GitHub Actions config - Add `sbt/java8-node`,`sbt/java11-node` and `sbt/java17-node`

sbt/java11-node/Dockerfile, sbt/java17-node/Dockerfile, sbt/java8-node/Dockerfile
Update: `Dockerfile`s in `sbt/java8-node`, `sbt/java11-node` and `sbt/java17-node`
- `ghcr.io/kevin-lee/sbt-java8:latest` => `ghcr.io/kevin-lee/sbt-java8:main`
- `ghcr.io/kevin-lee/sbt-java11:latest` => `ghcr.io/kevin-lee/sbt-java11:main`
- `ghcr.io/kevin-lee/sbt-java17:latest` => `ghcr.io/kevin-lee/sbt-java17:main`
=> Update: `Dockerfile`s in `sbt/java8-node`, `sbt/java11-node` and `sbt/java17-node`

.github/workflows/docker-publish.yml, README.md
Update README.md and update GitHub Actions to change scheduled build from daily build to weekly build
[skip ci]
=> Update README.md and update GitHub Actions to change scheduled build from daily build to weekly build

.github/workflows/docker-publish.yml
Update GitHub Actions config: Add a comment to the cron job
=> Update GitHub Actions config: Add a comment to the cron job

README.md
Update README.md with the latest release (v6)
=> Update README.md with the latest release (v6)

README.md
Update README.md with the latest release (v7)
=> Update README.md with the latest release (v7)

README.md
Update README.md with the latest release (v8)
[skip ci]
=> Update README.md with the latest release (v8)

README.md
Update `README.md` with the latest release (`v9`)
=> Update `README.md` with the latest release (`v9`)

README.md
Update README.md with the latest release (v10)
=> Update README.md with the latest release (v10)

README.md
Update `README.md` with the latest release (`v11`)
=> Update `README.md` with the latest release (`v11`)

java/java21/Dockerfile, java/java21/README.md
Close #89 - Add Docker image for Java 21
=> Close #89 - Add Docker image for Java 21

sbt/java21/Dockerfile, sbt/java21/README.md
Close #91 - Add a new image with Node + Java 21 (Adoptium) + SBT
=> Close #91 - Add a new image with Node + Java 21 (Adoptium) + SBT

sbt/java21-codecov/Dockerfile, sbt/java21-codecov/README.md
Close #93 - Add an image with Node + Java 21 (Adoptium) + SBT + Codecov
=> Close #93 - Add an image with Node + Java 21 (Adoptium) + SBT + Codecov

sbt/java21-jekyll/Dockerfile, sbt/java21-jekyll/README.md
Close #94 - Add an image with Node + Java 21 (Adoptium) + SBT + Jekyll
=> Close #94 - Add an image with Node + Java 21 (Adoptium) + SBT + Jekyll

sbt/java17-jekyll/README.md
Fix `README.md` of `sbt/java17-jekyll`
=> Fix `README.md` of `sbt/java17-jekyll`

README.md
Update `README.md` with the latest version info
=> Update `README.md` with the latest version info

README.md
Update README.md with the latest version info
=> Update README.md with the latest version info

.github/workflows/docker-publish.yml
Close #108 - Fix incorrect folder name for sbt with codecov and sbt with jekyll images
=> Close #108 - Fix incorrect folder name for sbt with codecov and sbt with jekyll images

.github/workflows/docker-publish.yml, java/liberica/java11/Dockerfile, java/liberica/java11/README.md, java/liberica/java17/Dockerfile, java/liberica/java17/README.md, java/liberica/java21/Dockerfile, java/liberica/java21/README.md, java/liberica/java8/Dockerfile, java/liberica/java8/README.md
Issue #116 - Add Docker images with BellSoft Liberica JDK
Add
- `java/liberica/java8`
- `java/liberica/java11`
- `java/liberica/java17`
- `java/liberica/java21`
=> Issue #116 - Add Docker images with BellSoft Liberica JDK

.github/workflows/docker-publish.yml, alpine/node/Dockerfile, alpine/node/README.md
Close #123 - Add a Docker image with Node installed on Alpine Linux
=> Close #123 - Add a Docker image with Node installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/liberica/java8/Dockerfile, alpine/java/liberica/java8/README.md
Close #125 - Add a Docker image with BellSoft Liberica Jdk 8 installed on Alpine Linux
=> Close #125 - Add a Docker image with BellSoft Liberica Jdk 8 installed on Alpine Linux

alpine/java/liberica/java8/Dockerfile
=> Remove unnecessary comments

.github/workflows/docker-publish.yml, alpine/java/liberica/java11/Dockerfile, alpine/java/liberica/java11/README.md
Close #128 - Add a Docker image with BellSoft Liberica Jdk 11 installed on Alpine Linux
=> Close #128 - Add a Docker image with BellSoft Liberica Jdk 11 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/liberica/java17/Dockerfile, alpine/java/liberica/java17/README.md
Close #130 - Add a Docker image with BellSoft Liberica Jdk 17 installed on Alpine Linux
=> Close #130 - Add a Docker image with BellSoft Liberica Jdk 17 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/liberica/java21/Dockerfile, alpine/java/liberica/java21/README.md
Close #131 - Add a Docker image with BellSoft Liberica Jdk 21 installed on Alpine Linux
=> Close #131 - Add a Docker image with BellSoft Liberica Jdk 21 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/temurin/java8/Dockerfile, alpine/java/temurin/java8/README.md
Close #133 - Add a Docker image with Eclipse Temurin JDK 8 installed on Alpine Linux
=> Close #133 - Add a Docker image with Eclipse Temurin JDK 8 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/temurin/java11/Dockerfile, alpine/java/temurin/java11/README.md
Close #134 - Add a Docker image with Eclipse Temurin JDK 11 installed on Alpine Linux
=> Close #134 - Add a Docker image with Eclipse Temurin JDK 11 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/temurin/java17/Dockerfile, alpine/java/temurin/java17/README.md
Close #135 - Add a Docker image with Eclipse Temurin JDK 17 installed on Alpine Linux
=> Close #135 - Add a Docker image with Eclipse Temurin JDK 17 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/temurin/java21/Dockerfile, alpine/java/temurin/java21/README.md
Close #136 - Add a Docker image with Eclipse Temurin JDK 21 installed on Alpine Linux
=> Close #136 - Add a Docker image with Eclipse Temurin JDK 21 installed on Alpine Linux

ubuntu/java/liberica/java11/Dockerfile, ubuntu/java/liberica/java17/Dockerfile, ubuntu/java/liberica/java21/Dockerfile, ubuntu/java/liberica/java8/Dockerfile, ubuntu/java/temurin/java11/Dockerfile, ubuntu/java/temurin/java17/Dockerfile, ubuntu/java/temurin/java21/Dockerfile, ubuntu/java/temurin/java8/Dockerfile
Add `ARG JAVA_VERSION` to each Java `Dockerfile` that doesn't already have it
=> Add ARG JAVA_VERSION to each Java Dockerfile that doesn't already have it

.github/workflows/docker-publish.yml, ubuntu/java/liberica/java8-jre/Dockerfile, ubuntu/java/liberica/java8-jre/README.md, ubuntu/java/temurin/java8-jre/Dockerfile, ubuntu/java/temurin/java8-jre/README.md
Close #145 - Add a Docker image with the JRE 8 installed on Ubuntu
=> Close #145 - Add a Docker image with the JRE 8 installed on Ubuntu

.github/workflows/docker-publish.yml, ubuntu/java/liberica/java11-jre/Dockerfile, ubuntu/java/liberica/java11-jre/README.md, ubuntu/java/temurin/java11-jre/Dockerfile, ubuntu/java/temurin/java11-jre/README.md
Close #146 - Add a Docker image with the JRE 11 installed on Ubuntu
=> Close #146 - Add a Docker image with the JRE 11 installed on Ubuntu

ubuntu/java/temurin/java11-jre/README.md, ubuntu/java/temurin/java11/README.md, ubuntu/java/temurin/java17/README.md, ubuntu/java/temurin/java21/README.md
Update README.md - fix incorrect info
=> Update README.md - fix incorrect info

.github/workflows/docker-publish.yml, ubuntu/java/liberica/java17-jre/Dockerfile, ubuntu/java/liberica/java17-jre/README.md, ubuntu/java/temurin/java17-jre/Dockerfile, ubuntu/java/temurin/java17-jre/README.md
Close #147 - Add a Docker image with the JRE 17 installed on Ubuntu
=> Close #147 - Add a Docker image with the JRE 17 installed on Ubuntu

.github/workflows/docker-publish.yml, ubuntu/java/liberica/java21-jre/Dockerfile, ubuntu/java/liberica/java21-jre/README.md, ubuntu/java/temurin/java21-jre/Dockerfile, ubuntu/java/temurin/java21-jre/README.md
Close #148 - Add a Docker image with the JRE 21 installed on Ubuntu
=> Close #148 - Add a Docker image with the JRE 21 installed on Ubuntu

alpine/java/temurin/java21-jre/Dockerfile, alpine/java/temurin/java21-jre/README.md
Close #204: Add a Docker image with Eclipse Temurin JRE 21 installed on Alpine Linux
=> Close #204: Add a Docker image with Eclipse Temurin JRE 21 installed on Alpine Linux

alpine/java/temurin/java17-jre/Dockerfile, alpine/java/temurin/java17-jre/README.md
Close #203: Add a Docker image with Eclipse Temurin JRE 17 installed on Alpine Linux
=> Close #203: Add a Docker image with Eclipse Temurin JRE 17 installed on Alpine Linux

alpine/java/liberica/java17-jre/Dockerfile, alpine/java/liberica/java17-jre/README.md
Close #207: Add a Docker image with BellSoft Liberica JRE 17 installed on Alpine Linux
=> Close #207: Add a Docker image with BellSoft Liberica JRE 17 installed on Alpine Linux

alpine/java/temurin/java11-jre/Dockerfile, alpine/java/temurin/java11-jre/README.md
Close #202: Add a Docker image with Eclipse Temurin JRE 11 installed on Alpine Linux
=> Close #202: Add a Docker image with Eclipse Temurin JRE 11 installed on Alpine Linux

alpine/java/liberica/java8-jre/Dockerfile, alpine/java/liberica/java8-jre/README.md
Close #205: Add a Docker image with BellSoft Liberica JRE 8 installed on Alpine Linux
=> Close #205: Add a Docker image with BellSoft Liberica JRE 8 installed on Alpine Linux

alpine/node/Dockerfile
Fix #225: Node is broken on Alpine Linux
=> Fix #225: Node is broken on Alpine Linux
