polynotes/polynote-spark-python/Dockerfile
Added: `PYSPARK_ALLOW_INSECURE_GATEWAY=1` to `polynote-spark-python` to share variable between Scala and Python
=> Added: PYSPARK_ALLOW_INSECURE_GATEWAY=1 to polynote-spark-python

polynotes/polynote-python/Dockerfile, polynotes/polynote-python/README.md, polynotes/polynote-spark-python/Dockerfile, polynotes/polynote-spark-python/README.md, polynotes/polynote-spark/Dockerfile, polynotes/polynote-spark/README.md, polynotes/polynote/Dockerfile, polynotes/polynote/README.md
Changed: back to Scala 2.11 as Spark 2.4.4 requires Scala 2.11
=> Changed: back to Scala 2.11 as Spark 2.4.4 requires Scala 2.11

sbt/java11/Dockerfile, sbt/java11/README.md, sbt/java8/Dockerfile, sbt/java8/README.md
Update s for java 8 and 11
- Upgrade Ubuntu from 20.04 to 22.04
- Upgrade sbt from 1.5.1 to 1.8.2
- adoptopenjdk => adoptium
- Update repository info
=> Update s for java 8 and 11

node/Dockerfile, node/README.md
Fix #28 - [node] Docker run fails to find node in non-interactive shells
=> Fix #28 - [node] Docker run fails to find node in non-interactive shells

.github/workflows/docker-publish.yml, sbt/java11-codecov/Dockerfile, sbt/java11-codecov/README.md, sbt/java17-codecov/Dockerfile, sbt/java17-codecov/README.md, sbt/java8-codecov/Dockerfile, sbt/java8-codecov/README.md
Add codecov to multiple Dockerfiles and Update Docker publish workflow
Created Dockerfiles to install codecov in sbt with java8, java11, and java17 environments and updated the Docker publish workflow accordingly to build the codecov Docker images. Also, added README for each version's instruction. Required for assessing code coverage in these respective environments.
=> Add codecov to multiple Dockerfiles and Update Docker publish workflow

.github/workflows/docker-publish.yml
Update docker-publish workflow to handle more tag patterns
The tagging pattern in the docker-publish workflow has been expanded to include `'v*.*'` and `'v*'`, in addition to the existing `'v*.*.*'`. This allows for greater flexibility in version tagging, accommodating different styles used across various projects.
=> Update docker-publish workflow to handle more tag patterns

README.md
Add README for kevin-docker project
A README.md file was created for the project 'kevin-docker'. This includes the version details of the Docker image used (sbt 1.8.2 in v1). This addition is meant to provide a summary and version details of the project to visitors and developers.
=> Add README for kevin-docker project

sbt/java11-jekyll/Dockerfile, sbt/java17-jekyll/Dockerfile, sbt/java8-jekyll/Dockerfile
Update Dockerfile to include apt update before install
The Dockerfiles for `sbt/java17-jekyll`, `sbt/java8-jekyll`, and `sbt/java11-jekyll` have been updated to include `apt update` before running the `apt-get install` command. This ensures that the package lists for upgrades and new package installations are always up-to-date before we start installing anything, preventing possible issues due to outdated package references.
=> Update Dockerfile to include apt update before install

README.md
Add v2 description to README.md
This commit expands the README.md to include information about the new Docker image version v2. Specifically, it details that v2 utilises sbt `1.8.3`, differing from v1 which uses sbt `1.8.2`. This offers clarity to users about the differences between the versions. [skip ci]
=> Add v2 description to README.md

README.md
Add `v3` description to `README.md`
A version 3(`v3`) description has been added to the `README.md` file. This version contains a Docker image with sbt `1.9.0`.
=> Add `v3` description to `README.md`

README.md
Added v4 details to `README.md`
- Updated `README` to include newly created 'v4', which comes along with SBT version upgrade from '1.9.0' to '1.9.1'.
=> Update SBT version from 1.9.0 to 1.9.1

.github/workflows/docker-publish.yml
Close #109 - Add missing Java 21 build in GitHub Actions configs
=> Close #109 - Add missing Java 21 build in GitHub Actions configs

.github/workflows/docker-publish.yml, sbt/liberica/java11-codecov/Dockerfile, sbt/liberica/java11-codecov/README.md, sbt/liberica/java11-jekyll/Dockerfile, sbt/liberica/java11-jekyll/README.md, sbt/liberica/java11/Dockerfile, sbt/liberica/java11/README.md, sbt/liberica/java17-codecov/Dockerfile, sbt/liberica/java17-codecov/README.md, sbt/liberica/java17-jekyll/Dockerfile, sbt/liberica/java17-jekyll/README.md, sbt/liberica/java17/Dockerfile, sbt/liberica/java17/README.md, sbt/liberica/java21-codecov/Dockerfile, sbt/liberica/java21-codecov/README.md, sbt/liberica/java21-jekyll/Dockerfile, sbt/liberica/java21-jekyll/README.md, sbt/liberica/java21/Dockerfile, sbt/liberica/java21/README.md, sbt/liberica/java8-codecov/Dockerfile, sbt/liberica/java8-codecov/README.md, sbt/liberica/java8-jekyll/Dockerfile, sbt/liberica/java8-jekyll/README.md, sbt/liberica/java8/Dockerfile, sbt/liberica/java8/README.md
Close #116 - Add Docker images with BellSoft Liberica JDK
Add
- `sbt/liberica/java8`
- `sbt/liberica/java8-codecov`
- `sbt/liberica/java8-jekyll`
- `sbt/liberica/java11`
- `sbt/liberica/java11-codecov`
- `sbt/liberica/java11-jekyll`
- `sbt/liberica/java17`
- `sbt/liberica/java17-codecov`
- `sbt/liberica/java17-jekyll`
- `sbt/liberica/java21`
- `sbt/liberica/java21-codecov`
- `sbt/liberica/java21-jekyll`
=> Close #116 - Add Docker images with BellSoft Liberica JDK

.github/workflows/docker-publish.yml
Fix GitHub Actions config - `build-alpine-java-liberica` had the wrong tag names for `alpine-javaN-liberica`
=> Fix GitHub Actions config - `build-alpine-java-liberica` had the wrong tag names for `alpine-javaN-liberica`

.github/workflows/docker-publish.yml
Fix GitHib Actions: fix incorrect setting in `build-alpine-java-liberica`
=> Fix GitHib Actions: fix incorrect setting in `build-alpine-java-liberica`

alpine/java/temurin/java8/Dockerfile
Fix #185 - Docker build for Temurin Java 8 on Alpine Linux is broken for ARM architecture
---
Fix: Handle architecture-specific Java 8 installation for Alpine
Eclipse Adoptium provides temurin-8-jdk for x86_64 but not for ARM64/aarch64 in APK format. This change implements architecture detection to install the optimal Java distribution for each platform:
- x86_64: Install Eclipse Temurin 8 from Adoptium APK repository
- ARM64/aarch64: Install OpenJDK 8 from Alpine's community repository
Changes:
- Add architecture detection (uname -m) during package installation
- Install temurin-8-jdk for x86_64 with Adoptium repository setup
- Install openjdk8-jdk for ARM64 using Alpine's native packages
- Create symlink to /usr/lib/jvm/default-jvm for unified JAVA_HOME
- Update JAVA_HOME and PATH to …
=> Fix #185 - Docker build for Temurin Java 8 on Alpine Linux is broken for ARM architecture

.github/workflows/docker-publish.yml, alpine/sbt/liberica/java21/Dockerfile, alpine/sbt/liberica/java21/README.md, alpine/sbt/temurin/java21/Dockerfile, alpine/sbt/temurin/java21/README.md
Close #161 - Add a Docker image with SBT + Jdk 21 installed on Alpine Linux
---
Add sbt support for Java 21 on Alpine Linux
- Enable `alpine-sbt-java21-liberica` and `alpine-sbt-java21-temurin` builds in CI workflow
- Add Dockerfile for Alpine + Java 21 Liberica + sbt 1.9.9
- Add Dockerfile for Alpine + Java 21 Temurin + sbt 1.9.9
- Include README documentation for both new Docker images
=> Close #161 - Add a Docker image with SBT + Jdk 21 installed on Alpine Linux

.github/workflows/docker-publish.yml, alpine/java/temurin/java11/Dockerfile
Fix #195: Docker build for Temurin Java 11 on Alpine Linux is broken for ARM architecture
Add multi-architecture support for `alpine-java11-temurin`
- Add architecture detection for `x86_64` vs `arm64` in Java 11 Alpine image
- Install Temurin JDK for AMD64 (`x86_64`) architecture
- Fallback to Alpine OpenJDK for ARM64 (`arm64`) and other architectures
- Create unified `JAVA_HOME` symlink for architecture-independent paths
=> Fix #195: Docker build for Temurin Java 11 on Alpine Linux is broken for ARM architecture

.github/workflows/docker-publish.yml, alpine/sbt/liberica/java11/Dockerfile, alpine/sbt/liberica/java11/README.md, alpine/sbt/temurin/java11/Dockerfile, alpine/sbt/temurin/java11/README.md
Close #159: Add a Docker image with SBT + Jdk 11 installed on Alpine Linux
- Add Dockerfile for Alpine + Java 11 Liberica + sbt 1.9.9
- Add Dockerfile for Alpine + Java 11 Temurin + sbt 1.9.9
- Include README documentation for both new Docker images
=> Close #159: Add a Docker image with SBT + Jdk 11 installed on Alpine Linux

alpine/java/liberica/java21-jre/Dockerfile, alpine/java/liberica/java21-jre/README.md
Close #213: Fix `JAVA_HOME` for Liberica JRE 21 on Alpine Linux
=> Close #213: Fix `JAVA_HOME` for Liberica JRE 21 on Alpine Linux

.github/workflows/docker-publish.yml
- Add Alpine JRE variants for Temurin JDK (`java8-jre`, `java11-jre`, `java17-jre`, `java21-jre`)
- Add Alpine JRE variants for Liberica JDK (`java8-jre`, `java11-jre`, `java17-jre`, `java21-jre`)
=> Add Alpine JRE variants to Docker build matrix

.github/workflows/docker-publish.yml, alpine/sbt/liberica/java8-codecov/Dockerfile, alpine/sbt/liberica/java8-codecov/README.md, alpine/sbt/temurin/java8-codecov/Dockerfile, alpine/sbt/temurin/java8-codecov/README.md
Close #246: Add an sbt Docker image with Java 8 and Codecov support for both Alpine Linux and Ubuntu Linux
Add Codecov integration to Java 8 SBT Docker images
- Add `alpine/sbt/liberica/java8-codecov` with Codecov uploader
- Add `alpine/sbt/temurin/java8-codecov` with Codecov uploader
- Include GPG verification and SHA256 checksum validation for security
- Add comprehensive README documentation for both variants
=> Close #246: Add an sbt Docker image with Java 8 and Codecov support for both Alpine Linux and Ubuntu Linux
